version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - jenyachosen
    assignees:
      - jenyachosen
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
